default: help

install:
	cd Src; make install; cp -f prediction ../

clean:
	cd Src; make clean

help:
	@echo "make clean    => Clean compiled objs and executables"
	@echo "make install  => Compile the program"
